project_id = "vybwydjazgltreionypl"

[functions.elevenlabs-tts]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.send-appointment-notification]
verify_jwt = false

[functions.analyze-crop-disease]
verify_jwt = false

[functions.generate-disease-pdf]
verify_jwt = false

[functions.esewa-initiate]
verify_jwt = false

[functions.esewa-verify]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.process-weather-alerts]
verify_jwt = false
